# Generated by Django 5.0.7 on 2026-06-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('prize_fund', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Призовой фонд')),
                ('prize_places', models.PositiveIntegerField(default=3, verbose_name='Количество призовых мест')),
                ('car_slots', models.PositiveIntegerField(verbose_name='Количество машин участников')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Прием заявок'), ('closed', 'Прием закрыт'), ('finished', 'Завершен')], default='draft', max_length=20, verbose_name='Статус')),
                ('cover_image', models.ImageField(blank=True, upload_to='festival_covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фестиваль',
                'verbose_name_plural': 'Фестивали',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FestivalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=160, verbose_name='Имя участника')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=80, verbose_name='Telegram')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город участника')),
                ('car_make', models.CharField(max_length=120, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=120, verbose_name='Модель')),
                ('car_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('engine', models.CharField(max_length=160, verbose_name='Мотор')),
                ('condition', models.TextField(verbose_name='Состояние машины')),
                ('tuning_details', models.TextField(blank=True, verbose_name='Тюнинг и особенности')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewing', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('moderator_note', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='festivals.festival', verbose_name='Фестиваль')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='application_cars/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='festivals.festivalapplication', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото машины',
                'verbose_name_plural': 'Фото машин',
            },
        ),
    ]
