# Generated by Django 5.0.7 on 2026-06-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120, verbose_name='Марка')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('engine', models.CharField(max_length=160, verbose_name='Мотор')),
                ('condition', models.TextField(verbose_name='Состояние машины')),
                ('tuning_details', models.TextField(blank=True, verbose_name='Тюнинг и особенности')),
                ('main_photo', models.ImageField(blank=True, upload_to='profile_cars/', verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Машина участника',
                'verbose_name_plural': 'Машины участников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=80, verbose_name='Telegram')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль участника',
                'verbose_name_plural': 'Профили участников',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='festivalapplication',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='applications', to='festivals.participantcar', verbose_name='Выбранные машины'),
        ),
        migrations.AddField(
            model_name='participantcar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='festivals.participantprofile', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='festivalapplication',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='festivals.participantprofile', verbose_name='Участник'),
        ),
    ]
